version: '2.1'

volumes:
    data:

services:
    database:
        image: kartoza/postgis:14-3.1
        volumes:
            - ../data:/database/var/lib/postgresql
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
            - ALLOW_IP_RANGE=0.0.0.0/0
            - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
        ports:
            - 55432:5432
        restart: on-failure
        healthcheck:
            test: "exit 0"
    web:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - database
            - redis
    celery:
        build: .
        command: celery -A backend beat -l INFO
        volumes:
            - .:/code/celery
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - web
            - redis
    redis:
        image: "redis:alpine"
