version: '2.1'

volumes:
    dbbackups:
    postgis-data:

services:
    _5db:
        image: kartoza/postgis:14-3.1
        volumes:
            - ../data:/_5db/var/lib/postgresql
            - ../dbbackups:/backups
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
            - ALLOW_IP_RANGE=0.0.0.0/0
            - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
        ports:
            - 25432:5432
        restart: on-failure
        healthcheck:
            test: "exit 0"
    dbbackups:
        image: kartoza/pg-backup:14.0
        hostname: pg-backups
        volumes:
            - ../dbbackups:/backups
        environment:
            - DUMPPREFIX=PG_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=_5db
            - POSTGRES_DBNAME=postgres
        restart: on-failure
        depends_on:
            _5db:
                condition: service_healthy
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - _5db
